Restore defining symbols to 1 in config.h
Fix macOS build error due to empty defined symbol:

/usr/include/dispatch/dispatch.h:38:45: error: expected value in expression
> #if !defined(HAVE_UNISTD_H) || HAVE_UNISTD_H